In [1]:
# https://nbviewer.org/github/amanchadha/coursera-deep-learning-specialization/blob/master/C1%20-%20Neural%20Networks%20and%20Deep%20Learning/Week%202/Python%20Basics%20with%20Numpy/Python_Basics_With_Numpy_v3a.ipynb

import numpy as np

In [2]:
# Exercise: Implement the sigmoid function using numpy.

# Instructions: x could now be either a real number, a vector, or a matrix. The data structures we use in numpy to represent these shapes (vectors, matrices...) 
# are called numpy arrays. You don't need to know more for now.

def sigmoid(x):
    return (1/(1+np.exp(-x)))

In [5]:
print(sigmoid(3))
x = np.array([1,2,3])
print(sigmoid(x))

0.9525741268224334
[0.73105858 0.88079708 0.95257413]


In [6]:
# 1.2 - Sigmoid gradient
# As you've seen in lecture, you will need to compute gradients to optimize loss functions using backpropagation. Let's code your first gradient function.

# Exercise: Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is:
#                                       sigmoid_derivative(x)=σ′(x)=σ(x)(1−σ(x))(2)

def sigmoid_grad(x):
    s = sigmoid(x)
    return s*(1-s)

In [9]:
print("sigmoid derivative:", sigmoid_grad(x))

sigmoid derivative: [0.19661193 0.10499359 0.04517666]


In [16]:
# Exercise: Implement image2vector() that takes an input of shape (length, height, 3) and returns a vector of shape (length*height*3, 1). For example, if you would 
# like to reshape an array v of shape (a, b, c) into a vector of shape (a*b,c) you would do:
#                               v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c

def image2vector(image):
    return image.reshape((image.shape[0] * image.shape[1] * image.shape[2], 1))
    

In [18]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print(image2vector(image))

[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [34]:
# Exercise: Implement normalizeRows() to normalize the rows of a matrix. After applying this function to an input matrix x, each row of x should be 
# a vector of unit length (meaning length 1).

def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """

    # THIS CODE WILL WORK IF U WANT keepdims TO BE false. WHEN keepdims IS false, THE NORMALIZED VALUE RETURNED IS A RANK 1 ARRAY WHICH 
    # DOES NOT BROADCAST TO FIT THE MATRIX WHEN WE DIVIDE xMod WITH x
    
    # xMod = np.linalg.norm(x, axis=1, keepdims=False)
    # print("xMod:", xMod.reshape(xMod.shape[0], 1))
    # return x/xMod.reshape(xMod.shape[0], 1)

    xMod = np.linalg.norm(x, axis=1, keepdims=True)
    print("xMod:", xMod)
    return x/xMod

In [35]:
x = np.array([
    [0, 3, 4],  
    [1, 6, 4]])
print("\nnormalizeRows(x) = " + str(normalizeRows(x)))

xMod: [[5.        ]
 [7.28010989]]

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [40]:
# Implement a softmax function using numpy. You can think of softmax as a normalizing function used when your algorithm needs to classify 
# two or more classes. You will learn more about softmax in the second course of this specialization.

# GRADED FUNCTION: softmax

def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (m,n).

    Argument:
    x -- A numpy matrix of shape (m,n)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (m,n)
    """
    x = np.exp(x)
    rowSum = np.sum(x, axis=1).reshape(x.shape[0], 1) # OR WE COUDLVE USED keepdims=True INSTEAD OF USING .reshape()
    return x/rowSum



In [42]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(t_x)))


softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [43]:
# Exercise: Implement the numpy vectorized version of the L1 loss. You may find the function abs(x) (absolute value of x) useful.

def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    diffArr = np.abs(y-yhat)
    return np.sum(diffArr)

In [44]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [47]:
# Exercise: Implement the numpy vectorized version of the L2 loss. There are several way of implementing the L2 loss but you may find the function np.dot() useful. 

def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """

    diffArr = (y-yhat)
    return np.dot(diffArr, diffArr)    

In [48]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43
